[2025-08-06T14:34:22.775-0400] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-08-06T14:34:22.781-0400] {taskinstance.py:2631} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_dag.dbt_tasks.dbt_run manual__2025-08-06T18:30:08.253381+00:00 [queued]>
[2025-08-06T14:34:22.784-0400] {taskinstance.py:2631} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_dag.dbt_tasks.dbt_run manual__2025-08-06T18:30:08.253381+00:00 [queued]>
[2025-08-06T14:34:22.784-0400] {taskinstance.py:2884} INFO - Starting attempt 2 of 7
[2025-08-06T14:34:22.804-0400] {taskinstance.py:2907} INFO - Executing <Task(BashOperator): dbt_tasks.dbt_run> on 2025-08-06 18:30:08.253381+00:00
[2025-08-06T14:34:22.807-0400] {standard_task_runner.py:72} INFO - Started process 27957 to run task
[2025-08-06T14:34:22.810-0400] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_dag', 'dbt_tasks.dbt_run', 'manual__2025-08-06T18:30:08.253381+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmph04q4mv1']
[2025-08-06T14:34:22.811-0400] {standard_task_runner.py:105} INFO - Job 6: Subtask dbt_tasks.dbt_run
[2025-08-06T14:34:22.844-0400] {task_command.py:467} INFO - Running <TaskInstance: dbt_dag.dbt_tasks.dbt_run manual__2025-08-06T18:30:08.253381+00:00 [running]> on host LAPTOP-OO6HSLFU.localdomain
[2025-08-06T14:34:22.889-0400] {taskinstance.py:3157} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='huy' AIRFLOW_CTX_DAG_ID='dbt_dag' AIRFLOW_CTX_TASK_ID='dbt_tasks.dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2025-08-06T18:30:08.253381+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-06T18:30:08.253381+00:00'
[2025-08-06T14:34:22.890-0400] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-08-06T14:34:22.891-0400] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-08-06T14:34:22.891-0400] {logging_mixin.py:190} INFO - Current task name:dbt_tasks.dbt_run state:running start_date:2025-08-06 18:34:22.781965+00:00
[2025-08-06T14:34:22.891-0400] {logging_mixin.py:190} INFO - Dag name:dbt_dag and current dag run status:running
[2025-08-06T14:34:22.891-0400] {taskinstance.py:740} INFO - ::endgroup::
[2025-08-06T14:34:22.892-0400] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-08-06T14:34:22.893-0400] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt run --project-dir /mnt/c/project/DBT/moviesDBT/dbt --profiles-dir /mnt/c/Users/huyng/.dbt']
[2025-08-06T14:34:22.899-0400] {subprocess.py:99} INFO - Output:
[2025-08-06T14:34:24.095-0400] {subprocess.py:106} INFO - [0m18:34:24  Running with dbt=1.8.8
[2025-08-06T14:34:24.475-0400] {subprocess.py:106} INFO - [0m18:34:24  Registered adapter: snowflake=1.8.4
[2025-08-06T14:34:24.602-0400] {subprocess.py:106} INFO - [0m18:34:24  Unable to do partial parsing because of a version mismatch
[2025-08-06T14:34:26.654-0400] {subprocess.py:106} INFO - [0m18:34:26  [[33mWARNING[0m]: Deprecated functionality
[2025-08-06T14:34:26.654-0400] {subprocess.py:106} INFO - The `tests` config has been renamed to `data_tests`. Please see
[2025-08-06T14:34:26.655-0400] {subprocess.py:106} INFO - https://docs.getdbt.com/docs/build/data-tests#new-data_tests-syntax for more
[2025-08-06T14:34:26.655-0400] {subprocess.py:106} INFO - information.
[2025-08-06T14:34:26.664-0400] {subprocess.py:106} INFO - [0m18:34:26  [[33mWARNING[0m]: Did not find matching node for patch with name 'dim_movie' in the 'models' section of file 'models/schema.yml'
[2025-08-06T14:34:26.666-0400] {subprocess.py:106} INFO - [0m18:34:26  [[33mWARNING[0m]: Did not find matching node for patch with name 'dim_user' in the 'models' section of file 'models/schema.yml'
[2025-08-06T14:34:26.668-0400] {subprocess.py:106} INFO - [0m18:34:26  [[33mWARNING[0m]: Did not find matching node for patch with name 'dim_genome_tag' in the 'models' section of file 'models/schema.yml'
[2025-08-06T14:34:26.670-0400] {subprocess.py:106} INFO - [0m18:34:26  [[33mWARNING[0m]: Did not find matching node for patch with name 'fact_movie_rating' in the 'models' section of file 'models/schema.yml'
[2025-08-06T14:34:26.672-0400] {subprocess.py:106} INFO - [0m18:34:26  [[33mWARNING[0m]: Did not find matching node for patch with name 'fct_genome_scoring' in the 'models' section of file 'models/schema.yml'
[2025-08-06T14:34:26.815-0400] {subprocess.py:106} INFO - [0m18:34:26  [[33mWARNING[0m]: Test 'test.moviesDBT.not_null_dim_movie_movie_id.fd05907b20' (models/schema.yml) depends on a node named 'dim_movie' in package '' which was not found
[2025-08-06T14:34:26.816-0400] {subprocess.py:106} INFO - [0m18:34:26  [[33mWARNING[0m]: Test 'test.moviesDBT.not_null_dim_movie_title.412500e257' (models/schema.yml) depends on a node named 'dim_movie' in package '' which was not found
[2025-08-06T14:34:26.817-0400] {subprocess.py:106} INFO - [0m18:34:26  [[33mWARNING[0m]: Test 'test.moviesDBT.not_null_dim_user_user_id.4b202b08a3' (models/schema.yml) depends on a node named 'dim_user' in package '' which was not found
[2025-08-06T14:34:26.818-0400] {subprocess.py:106} INFO - [0m18:34:26  [[33mWARNING[0m]: Test 'test.moviesDBT.not_null_dim_genome_tag_tag_id.7e68d3ddfa' (models/schema.yml) depends on a node named 'dim_genome_tag' in package '' which was not found
[2025-08-06T14:34:26.819-0400] {subprocess.py:106} INFO - [0m18:34:26  [[33mWARNING[0m]: Test 'test.moviesDBT.not_null_dim_genome_tag_tag.3f161a3827' (models/schema.yml) depends on a node named 'dim_genome_tag' in package '' which was not found
[2025-08-06T14:34:26.819-0400] {subprocess.py:106} INFO - [0m18:34:26  [[33mWARNING[0m]: Test 'test.moviesDBT.not_null_fact_movie_rating_user_id.9ae666a74d' (models/schema.yml) depends on a node named 'fact_movie_rating' in package '' which was not found
[2025-08-06T14:34:26.820-0400] {subprocess.py:106} INFO - [0m18:34:26  [[33mWARNING[0m]: Test 'test.moviesDBT.not_null_fact_movie_rating_movie_id.93257e09c6' (models/schema.yml) depends on a node named 'fact_movie_rating' in package '' which was not found
[2025-08-06T14:34:26.821-0400] {subprocess.py:106} INFO - [0m18:34:26  [[33mWARNING[0m]: Test 'test.moviesDBT.relationships_fact_movie_rating_movie_id__movie_id__ref_dim_movie_.7c4f52d7e0' (models/schema.yml) depends on a node named 'dim_movie' in package '' which was not found
[2025-08-06T14:34:26.822-0400] {subprocess.py:106} INFO - [0m18:34:26  [[33mWARNING[0m]: Test 'test.moviesDBT.relationships_fact_movie_rating_movie_id__movie_id__ref_dim_movie_.7c4f52d7e0' (models/schema.yml) depends on a node named 'fact_movie_rating' in package '' which was not found
[2025-08-06T14:34:26.822-0400] {subprocess.py:106} INFO - [0m18:34:26  [[33mWARNING[0m]: Test 'test.moviesDBT.not_null_fact_movie_rating_rating.1c192c6490' (models/schema.yml) depends on a node named 'fact_movie_rating' in package '' which was not found
[2025-08-06T14:34:26.823-0400] {subprocess.py:106} INFO - [0m18:34:26  [[33mWARNING[0m]: Test 'test.moviesDBT.not_null_fct_genome_scoring_movie_id.459137e687' (models/schema.yml) depends on a node named 'fct_genome_scoring' in package '' which was not found
[2025-08-06T14:34:26.824-0400] {subprocess.py:106} INFO - [0m18:34:26  [[33mWARNING[0m]: Test 'test.moviesDBT.not_null_fct_genome_scoring_tag_id.6e2dbe3c4c' (models/schema.yml) depends on a node named 'fct_genome_scoring' in package '' which was not found
[2025-08-06T14:34:26.825-0400] {subprocess.py:106} INFO - [0m18:34:26  [[33mWARNING[0m]: Test 'test.moviesDBT.not_null_fct_genome_scoring_relevance_score.fc413c52e6' (models/schema.yml) depends on a node named 'fct_genome_scoring' in package '' which was not found
[2025-08-06T14:34:26.890-0400] {subprocess.py:106} INFO - [0m18:34:26  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-08-06T14:34:26.891-0400] {subprocess.py:106} INFO - There are 2 unused configuration paths:
[2025-08-06T14:34:26.891-0400] {subprocess.py:106} INFO - - models.moviesDBT.dim
[2025-08-06T14:34:26.891-0400] {subprocess.py:106} INFO - - models.moviesDBT.fact
[2025-08-06T14:34:27.056-0400] {subprocess.py:106} INFO - [0m18:34:27  Found 1 model, 1 snapshot, 6 sources, 570 macros
[2025-08-06T14:34:27.058-0400] {subprocess.py:106} INFO - [0m18:34:27
[2025-08-06T14:34:28.596-0400] {subprocess.py:106} INFO - [0m18:34:28  Concurrency: 1 threads (target='dev')
[2025-08-06T14:34:28.597-0400] {subprocess.py:106} INFO - [0m18:34:28
[2025-08-06T14:34:28.605-0400] {subprocess.py:106} INFO - [0m18:34:28  1 of 1 START sql table model DEV.stage_tag ..................................... [RUN]
[2025-08-06T14:34:30.658-0400] {subprocess.py:106} INFO - [0m18:34:30  1 of 1 OK created sql table model DEV.stage_tag ................................ [[32mSUCCESS 1[0m in 2.05s]
[2025-08-06T14:34:30.663-0400] {subprocess.py:106} INFO - [0m18:34:30
[2025-08-06T14:34:30.664-0400] {subprocess.py:106} INFO - [0m18:34:30  Finished running 1 table model in 0 hours 0 minutes and 3.60 seconds (3.60s).
[2025-08-06T14:34:30.735-0400] {subprocess.py:106} INFO - [0m18:34:30
[2025-08-06T14:34:30.736-0400] {subprocess.py:106} INFO - [0m18:34:30  [32mCompleted successfully[0m
[2025-08-06T14:34:30.737-0400] {subprocess.py:106} INFO - [0m18:34:30
[2025-08-06T14:34:30.737-0400] {subprocess.py:106} INFO - [0m18:34:30  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2025-08-06T14:34:31.391-0400] {subprocess.py:110} INFO - Command exited with return code 0
[2025-08-06T14:34:31.413-0400] {taskinstance.py:349} INFO - ::group::Post task execution logs
[2025-08-06T14:34:31.413-0400] {taskinstance.py:361} INFO - Marking task as SUCCESS. dag_id=dbt_dag, task_id=dbt_tasks.dbt_run, run_id=manual__2025-08-06T18:30:08.253381+00:00, execution_date=20250806T183008, start_date=20250806T183422, end_date=20250806T183431
[2025-08-06T14:34:31.431-0400] {logging_mixin.py:190} INFO - Task instance in success state
[2025-08-06T14:34:31.431-0400] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-08-06T14:34:31.431-0400] {logging_mixin.py:190} INFO - Dag name:dbt_dag queued_at:2025-08-06 18:30:08.266216+00:00
[2025-08-06T14:34:31.431-0400] {logging_mixin.py:190} INFO - Task hostname:LAPTOP-OO6HSLFU.localdomain operator:BashOperator
[2025-08-06T14:34:31.472-0400] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-08-06T14:34:31.481-0400] {taskinstance.py:3924} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-06T14:34:31.481-0400] {local_task_job_runner.py:245} INFO - ::endgroup::
