[2025-08-06T14:47:32.560-0400] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-08-06T14:47:32.569-0400] {taskinstance.py:2631} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_dag1.dbt_tasks.dbt_debug manual__2025-08-06T18:47:28.830917+00:00 [queued]>
[2025-08-06T14:47:32.572-0400] {taskinstance.py:2631} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_dag1.dbt_tasks.dbt_debug manual__2025-08-06T18:47:28.830917+00:00 [queued]>
[2025-08-06T14:47:32.573-0400] {taskinstance.py:2884} INFO - Starting attempt 1 of 6
[2025-08-06T14:47:32.584-0400] {taskinstance.py:2907} INFO - Executing <Task(BashOperator): dbt_tasks.dbt_debug> on 2025-08-06 18:47:28.830917+00:00
[2025-08-06T14:47:32.587-0400] {standard_task_runner.py:72} INFO - Started process 31300 to run task
[2025-08-06T14:47:32.590-0400] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_dag1', 'dbt_tasks.dbt_debug', 'manual__2025-08-06T18:47:28.830917+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmpq2xd66wo']
[2025-08-06T14:47:32.591-0400] {standard_task_runner.py:105} INFO - Job 8: Subtask dbt_tasks.dbt_debug
[2025-08-06T14:47:32.624-0400] {task_command.py:467} INFO - Running <TaskInstance: dbt_dag1.dbt_tasks.dbt_debug manual__2025-08-06T18:47:28.830917+00:00 [running]> on host LAPTOP-OO6HSLFU.localdomain
[2025-08-06T14:47:32.666-0400] {taskinstance.py:3157} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='huy' AIRFLOW_CTX_DAG_ID='dbt_dag1' AIRFLOW_CTX_TASK_ID='dbt_tasks.dbt_debug' AIRFLOW_CTX_EXECUTION_DATE='2025-08-06T18:47:28.830917+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-06T18:47:28.830917+00:00'
[2025-08-06T14:47:32.668-0400] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-08-06T14:47:32.668-0400] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-08-06T14:47:32.668-0400] {logging_mixin.py:190} INFO - Current task name:dbt_tasks.dbt_debug state:running start_date:2025-08-06 18:47:32.569447+00:00
[2025-08-06T14:47:32.668-0400] {logging_mixin.py:190} INFO - Dag name:dbt_dag1 and current dag run status:running
[2025-08-06T14:47:32.668-0400] {taskinstance.py:740} INFO - ::endgroup::
[2025-08-06T14:47:32.669-0400] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-08-06T14:47:32.670-0400] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt debug --project-dir /mnt/c/project/DBT/moviesDBT/dbt --profiles-dir /mnt/c/Users/huyng/.dbt']
[2025-08-06T14:47:32.676-0400] {subprocess.py:99} INFO - Output:
[2025-08-06T14:47:34.050-0400] {subprocess.py:106} INFO - [0m18:47:34  Running with dbt=1.8.8
[2025-08-06T14:47:34.069-0400] {subprocess.py:106} INFO - [0m18:47:34  dbt version: 1.8.8
[2025-08-06T14:47:34.069-0400] {subprocess.py:106} INFO - [0m18:47:34  python version: 3.12.3
[2025-08-06T14:47:34.070-0400] {subprocess.py:106} INFO - [0m18:47:34  python path: /home/huynguyen2741/airflow_venv/bin/python3
[2025-08-06T14:47:34.071-0400] {subprocess.py:106} INFO - [0m18:47:34  os info: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.39
[2025-08-06T14:47:34.397-0400] {subprocess.py:106} INFO - [0m18:47:34  Using profiles dir at /mnt/c/Users/huyng/.dbt
[2025-08-06T14:47:34.398-0400] {subprocess.py:106} INFO - [0m18:47:34  Using profiles.yml file at /mnt/c/Users/huyng/.dbt/profiles.yml
[2025-08-06T14:47:34.399-0400] {subprocess.py:106} INFO - [0m18:47:34  Using dbt_project.yml file at /mnt/c/project/DBT/moviesDBT/dbt/dbt_project.yml
[2025-08-06T14:47:34.400-0400] {subprocess.py:106} INFO - [0m18:47:34  adapter type: snowflake
[2025-08-06T14:47:34.401-0400] {subprocess.py:106} INFO - [0m18:47:34  adapter version: 1.8.4
[2025-08-06T14:47:34.480-0400] {subprocess.py:106} INFO - [0m18:47:34  Configuration:
[2025-08-06T14:47:34.480-0400] {subprocess.py:106} INFO - [0m18:47:34    profiles.yml file [[32mOK found and valid[0m]
[2025-08-06T14:47:34.481-0400] {subprocess.py:106} INFO - [0m18:47:34    dbt_project.yml file [[32mOK found and valid[0m]
[2025-08-06T14:47:34.482-0400] {subprocess.py:106} INFO - [0m18:47:34  Required dependencies:
[2025-08-06T14:47:34.496-0400] {subprocess.py:106} INFO - [0m18:47:34   - git [[32mOK found[0m]
[2025-08-06T14:47:34.496-0400] {subprocess.py:106} INFO - 
[2025-08-06T14:47:34.497-0400] {subprocess.py:106} INFO - [0m18:47:34  Connection:
[2025-08-06T14:47:34.497-0400] {subprocess.py:106} INFO - [0m18:47:34    account: YVLKKXT-JTC82318
[2025-08-06T14:47:34.498-0400] {subprocess.py:106} INFO - [0m18:47:34    user: dbt
[2025-08-06T14:47:34.499-0400] {subprocess.py:106} INFO - [0m18:47:34    database: MOVIELENS_DB
[2025-08-06T14:47:34.500-0400] {subprocess.py:106} INFO - [0m18:47:34    warehouse: COMPUTE_WH
[2025-08-06T14:47:34.501-0400] {subprocess.py:106} INFO - [0m18:47:34    role: TRANSFORM
[2025-08-06T14:47:34.501-0400] {subprocess.py:106} INFO - [0m18:47:34    schema: DEV
[2025-08-06T14:47:34.502-0400] {subprocess.py:106} INFO - [0m18:47:34    authenticator: None
[2025-08-06T14:47:34.503-0400] {subprocess.py:106} INFO - [0m18:47:34    oauth_client_id: None
[2025-08-06T14:47:34.504-0400] {subprocess.py:106} INFO - [0m18:47:34    query_tag: None
[2025-08-06T14:47:34.505-0400] {subprocess.py:106} INFO - [0m18:47:34    client_session_keep_alive: False
[2025-08-06T14:47:34.505-0400] {subprocess.py:106} INFO - [0m18:47:34    host: None
[2025-08-06T14:47:34.506-0400] {subprocess.py:106} INFO - [0m18:47:34    port: None
[2025-08-06T14:47:34.507-0400] {subprocess.py:106} INFO - [0m18:47:34    proxy_host: None
[2025-08-06T14:47:34.508-0400] {subprocess.py:106} INFO - [0m18:47:34    proxy_port: None
[2025-08-06T14:47:34.509-0400] {subprocess.py:106} INFO - [0m18:47:34    protocol: None
[2025-08-06T14:47:34.509-0400] {subprocess.py:106} INFO - [0m18:47:34    connect_retries: 1
[2025-08-06T14:47:34.510-0400] {subprocess.py:106} INFO - [0m18:47:34    connect_timeout: None
[2025-08-06T14:47:34.511-0400] {subprocess.py:106} INFO - [0m18:47:34    retry_on_database_errors: False
[2025-08-06T14:47:34.511-0400] {subprocess.py:106} INFO - [0m18:47:34    retry_all: False
[2025-08-06T14:47:34.512-0400] {subprocess.py:106} INFO - [0m18:47:34    insecure_mode: False
[2025-08-06T14:47:34.513-0400] {subprocess.py:106} INFO - [0m18:47:34    reuse_connections: None
[2025-08-06T14:47:34.514-0400] {subprocess.py:106} INFO - [0m18:47:34  Registered adapter: snowflake=1.8.4
[2025-08-06T14:47:35.107-0400] {subprocess.py:106} INFO - [0m18:47:35    Connection test: [[32mOK connection ok[0m]
[2025-08-06T14:47:35.107-0400] {subprocess.py:106} INFO - 
[2025-08-06T14:47:35.108-0400] {subprocess.py:106} INFO - [0m18:47:35  [32mAll checks passed![0m
[2025-08-06T14:47:35.515-0400] {subprocess.py:110} INFO - Command exited with return code 0
[2025-08-06T14:47:35.541-0400] {taskinstance.py:349} INFO - ::group::Post task execution logs
[2025-08-06T14:47:35.542-0400] {taskinstance.py:361} INFO - Marking task as SUCCESS. dag_id=dbt_dag1, task_id=dbt_tasks.dbt_debug, run_id=manual__2025-08-06T18:47:28.830917+00:00, execution_date=20250806T184728, start_date=20250806T184732, end_date=20250806T184735
[2025-08-06T14:47:35.559-0400] {logging_mixin.py:190} INFO - Task instance in success state
[2025-08-06T14:47:35.559-0400] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-08-06T14:47:35.559-0400] {logging_mixin.py:190} INFO - Dag name:dbt_dag1 queued_at:2025-08-06 18:47:28.837183+00:00
[2025-08-06T14:47:35.559-0400] {logging_mixin.py:190} INFO - Task hostname:LAPTOP-OO6HSLFU.localdomain operator:BashOperator
[2025-08-06T14:47:35.570-0400] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-08-06T14:47:35.583-0400] {taskinstance.py:3924} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-08-06T14:47:35.589-0400] {local_task_job_runner.py:245} INFO - ::endgroup::
